services:
  postgres:
    image: postgres:15
    container_name: tijara-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tijara
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tijara-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: